# om namah shivaya

service: default
runtime: nodejs14
instance_class: F1
automatic_scaling:
  min_instances: 0
  max_instances: 1
  target_cpu_utilization: 0.90
handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
vpc_access_connector:
  # replace GCP_PROJECT_ID with your gcp project id
  # replace GCP_REGION with your gcp region
  name: projects/GCP_PROJECT_ID/locations/GCP_REGION/connectors/hello-redis-vpc-connector
